### ISSUE TITLE
换一张图片无法识别

### ISSUE THREAD

**Issue by DuanShengqi** [cmd23333/Faster-rcnn-tensorflow2.x#6]
加载了预训练模型后，只有dataset[1]中的img是可以预测的，换一张图片感觉就框的不准了，是模型迭代太少了吗？

**Comment by cmd23333** [comment]
trainer.py第75行， dataset[1]改成dataset[i]
为了调试和测试方便，只用了第一张图片训练。。。

**Comment by DuanShengqi** [comment]
学长，问一下整个数据集你是迭代了多少轮才有效果的？我感觉收敛的速度有点慢呢。
